### ISSUE TITLE
Some problems encountered when running locally

### ISSUE THREAD

**Issue by lanzhixi** [Tauffer-Consulting/domino#86]
I'm a fan of this project, but I've encountered a problem when doing local development, as follows:
1. After I forked a github repository, I switched to the dev branch and ran the following commands:
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/6b2e1a0f-4645-453a-9e3a-21aab70f6b33)
2. Then the front container exited abnormally. After checking the log, I tried to solve this problem but failed.(forgive me for being a rookie😭）
![Snap (2)](https://github.com/Tauffer-Consulting/domino/assets/114967305/cbda4f99-2d47-4a07-bff2-9c3af88d23b6)
3. So I deleted the front container, entered the front folder directly in the terminal, manually installed dependencies, and then started the project successfully.
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/3d6f999f-d623-4e56-bd05-f6fe043477aa)
4. After entering the system, the workflow can be created normally, but an error is reported to view the created workflow and cannot be viewed.Is this an error caused by my operation?
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/69a37d8f-fe7d-403d-97c0-6d39cfdd0959)

**Comment by luiztauffer** [comment]
hey @lanzhixi , thanks for bringing those problems to our attention!
We're still working on fixing some of the bugs, and improving the experience in local development. But this bug you reported is a known issue, I'll give you a couple of suggestions on how to solve it:

1. when using the local dev docker-compose file, you can run it with:
```
docker compose -f docker-compose-dev.yaml up --build
```
the `--build` flag makes sure you're using images built using your local source code. Otherwise, it will download the published images, which are not up to date. When the current dev branch gets merged, a lot of these problems will disappear. 
The local dev experience will also improve a lot with the coming changes in the CLI, which will accept a new `--dev` flag.

2. If you're still getting those bugs, I'd suggest you clean your docker images, cache and volumes (beware that this will clean ALL docker cache, including other images you might be using):
```
docker system prune --all
docker volume prune
sudo service docker restart
```

and after that, run the docker compose command again. It should work now.

**Comment by lanzhixi** [comment]
Thank you very much, I understand.

**Comment by lanzhixi** [comment]
I apologize for my ignorance, and I thank you for your guidance. I was not familiar with Airflow before. To initialize it on a Linux platform, I first needed to execute `mkdir -p ./dags ./logs ./plugins ./config` and `echo -e "AIRFLOW_UID=$(id -u)" > .env`, then build it using `docker-compose-dev.yaml`. As for the issue of the frontend container stopping, I found a temporary solution. By executing `cd /front` before building with Docker Compose, and then running `yarn` to install dependencies, the frontend container will not stop after building. The system can then run normally.Now you can close this issue.

**Comment by luiztauffer** [comment]
thank you for your feedback @lanzhixi 
indeed, if you run docker compose directly on the compose file we have at the root folder, you'll need the yarn installation locally, and that's because that docker compose file is for local development and we're mounting some local volumes there, including the frontend path

the most stable (and easiest) way, as of now, to run it locally, is through compose but using our cli. You can read more in the [docs](https://tauffer-consulting.github.io/domino-docs/docs/run_domino/run_locally_compose)
